spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    name: sa
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: h2
    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true